[book]
authors = ["Paul ADAM"]
language = "fr"
multilingual = false
src = "src"
title = "Sinfonie ENS Rennes"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/pauladam94/Sinfonie.io"